### ISSUE TITLE
when testing multi - svc.units[0] IndexError: list index out of range

### ISSUE THREAD

**Issue by ryan-beisner** [Ubuntu-Solutions-Engineering/openstack-tests#1]
After a default unattended multi install, I try to run the multi tests and hit an issue.  Note, I've added an add'l info log line in validator.py to dump the svc.units value.
```
jenkins@juju-osci-machine-13:~/tools/openstack-testsâŸ« juju stat --format tabular
[Services]                
NAME                      STATUS  EXPOSED CHARM                                    
glance                    unknown false   cs:trusty/glance-24                      
glance-simplestreams-sync unknown false   local:trusty/glance-simplestreams-sync-0 
keystone                  unknown false   cs:trusty/keystone-28                    
mysql                     unknown false   cs:trusty/mysql-28                       
neutron-api               unknown false   cs:trusty/neutron-api-17                 
neutron-gateway           unknown false   cs:trusty/neutron-gateway-5              
neutron-openvswitch               false   cs:trusty/neutron-openvswitch-9          
nova-cloud-controller     unknown false   cs:trusty/nova-cloud-controller-60       
nova-compute              unknown false   cs:trusty/nova-compute-26                
ntp                               false   cs:trusty/ntp-11                         
openstack-dashboard       unknown false   cs:trusty/openstack-dashboard-16         
rabbitmq-server           unknown false   cs:trusty/rabbitmq-server-34             

[Units]                     
ID                          WORKLOAD-STATE AGENT-STATE VERSION MACHINE PORTS                               PUBLIC-ADDRESS             MESSAGE 
glance-simplestreams-sync/0 unknown        idle        1.24.5  3/lxc/4                                     10.245.171.54                      
glance/0                    unknown        idle        1.24.5  3/lxc/5 9292/tcp                            10.245.171.55                      
keystone/0                  unknown        idle        1.24.5  3/lxc/2                                     10.245.171.51                      
mysql/0                     unknown        idle        1.24.5  3/lxc/0                                     10.245.171.164                     
neutron-api/0               unknown        idle        1.24.5  3/lxc/6 9696/tcp                            10.245.171.49                      
neutron-gateway/0           unknown        idle        1.24.5  2                                           cylindrical-base.dellstack         
  ntp/0                     unknown        idle        1.24.5                                              cylindrical-base.dellstack         
nova-cloud-controller/0     unknown        idle        1.24.5  3/lxc/3 3333/tcp,8773/tcp,8774/tcp,9696/tcp 10.245.171.53                      
nova-compute/0              unknown        idle        1.24.5  1                                           fat-machine.dellstack              
  neutron-openvswitch/0     unknown        idle        1.24.5                                              fat-machine.dellstack              
  ntp/1                     unknown        idle        1.24.5                                              fat-machine.dellstack              
openstack-dashboard/0       unknown        idle        1.24.5  3/lxc/7 80/tcp,443/tcp                      10.245.171.50                      
rabbitmq-server/0           unknown        idle        1.24.5  3/lxc/1 5672/tcp                            10.245.171.52                      

[Machines] 
ID         STATE   VERSION DNS                        INS-ID                                                         SERIES HARDWARE                                                                                                                    
0          started 1.24.5  phony-trick.dellstack      /MAAS/api/1.0/nodes/node-d4510508-8228-11e4-9105-d4bed9a84493/ trusty arch=amd64 cpu-cores=8 mem=49152M tags=node-d4510508-8228-11e4-9105-d4bed9a84493,uosci,compute                              
1          started 1.24.5  fat-machine.dellstack      /MAAS/api/1.0/nodes/node-d4692494-8228-11e4-8078-d4bed9a84493/ trusty arch=amd64 cpu-cores=8 mem=49152M tags=node-d4692494-8228-11e4-8078-d4bed9a84493,uosci,storage                              
2          started 1.24.5  cylindrical-base.dellstack /MAAS/api/1.0/nodes/node-d65842d0-8228-11e4-9105-d4bed9a84493/ trusty arch=amd64 cpu-cores=8 mem=49152M tags=node-d65842d0-8228-11e4-9105-d4bed9a84493,uosci,gateway                              
3          started 1.24.5  grizzled-family.dellstack  /MAAS/api/1.0/nodes/node-d74ee982-8228-11e4-8078-d4bed9a84493/ trusty arch=amd64 cpu-cores=8 mem=49152M tags=node-d74ee982-8228-11e4-8078-d4bed9a84493,uosci,storage,object_zone_1,object_storage 

jenkins@juju-osci-machine-13:~/tools/openstack-testsâŸ« sudo -E openstack-ci -a -c ~/config-multi.yaml 
[INFO  â€¢ 14:05:11 â€¢ openstackci] Initializing tests.
[INFO  â€¢ 14:05:11 â€¢ openstackci] Authenticated against juju
[INFO  â€¢ 14:05:11 â€¢ openstackci] Test: Verifies the multi install deployed.
[INFO  â€¢ 14:05:11 â€¢ openstackci] svc.units: [<Unit: mysql/0, Machine: 3/lxc/0, State: started>]
[INFO  â€¢ 14:05:11 â€¢ openstackci] Checking mysql/0
[INFO  â€¢ 14:05:11 â€¢ openstackci] svc.units: [<Unit: neutron-gateway/0, Machine: 2, State: started>]
[INFO  â€¢ 14:05:11 â€¢ openstackci] Checking neutron-gateway/0
[INFO  â€¢ 14:05:11 â€¢ openstackci] svc.units: [<Unit: glance/0, Machine: 3/lxc/5, State: started>]
[INFO  â€¢ 14:05:11 â€¢ openstackci] Checking glance/0
[INFO  â€¢ 14:05:11 â€¢ openstackci] svc.units: []
Traceback (most recent call last):
  File "/usr/bin/openstack-ci", line 85, in <module>
    tester.run_all_tests()
  File "/usr/share/openstack-ci/openstackci/tester.py", line 132, in run_all_tests
    t.run()
  File "/var/lib/jenkins/tools/openstack-tests/quality/00_multi_deployed.py", line 30, in run
    ret, services = validate.is_services_started()
  File "/usr/share/openstack-ci/openstackci/validator.py", line 37, in is_services_started
    unit = svc.units[0]
IndexError: list index out of range
```

**Comment by battlemidget** [comment]
Re-doing the tests completely
